block-beta
    columns 4
    d ("Dados"):4

    quali ("Qualitativos</br>(categóricos)"):2
    quant ("Quantitativos</br>(numéricos)"):2

    nom ("Nominal")
    ord ("Ordinal")
    int ("Intervalo</br>(relativa)")
    abs ("Absoluta</br>(racio)")

    space space
    block:prec:2
        disc("Discretos")
        cont("Contínuos")
    end

    style prec rx:10,ry:10